version: '3'

services:
    db:
      image: postgres:12.1
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres

    web:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./app/:/usr/src/app/
      environment:
        - DB_NAME=postgres
        - DB_USER=postgres
        - DB_PASSWORD=postgres
        - DB_HOST=db
      ports:
        - "8000:8000"
      depends_on:
        - db

volumes:
  postgres_data:
